apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-evict: true
spec:
  nodeSelector:
    role: jenkins-agent
  tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: jenkins-agent

# The configs above this line are mandatory. Only edit them if you really know what you're doing.

  containers:
    - name: jnlp
      image: 618430153747.dkr.ecr.us-east-1.amazonaws.com/jenkins-agent-jnlp
      securityContext:
        privileged: true
      env:
        - name: DIND
          value: "true"
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 14Gi
          cpu: 7500m
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1 # Prefer instances with instance store volumes (NVMe SSD)
          preference:
            matchExpressions:
              - key: karpenter.k8s.aws/instance-local-nvme
                operator: Exists
        - weight: 1 # Prefer network optimized instances
          preference:
            matchExpressions:
              - key: karpenter.k8s.aws/instance-category
                operator: In
                values: ["n"]