apiVersion: v1
kind: Pod
metadata:
  annotations:
    karpenter.sh/do-not-evict: true
spec:
  nodeSelector:
    role: jenkins-agent
  tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: jenkins-agent

# The configs above this line are mandatory. Only edit them if you really know what you're doing.

  containers:
    - name: jnlp
      image: 618430153747.dkr.ecr.us-east-1.amazonaws.com/jenkins-agent-jnlp
      securityContext:
        privileged: true
      env:
        - name: DIND
          value: "true"
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 14Gi
          cpu: 7500m
      volumeMounts:
        - mountPath: /home/jenkins/agent/.m2
          name: global-cache
    - name: sonar
      image: sonarsource/sonar-scanner-cli
      command: ["sleep"]
      args: ["infinity"]
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 14Gi
          cpu: 7500m
    - name: maven
      image: quay.io/quarkus/centos-quarkus-maven:22.0-java11
      command: ["sleep"]
      args: ["infinity"]
      securityContext:
        runAsUser: 1000
        privileged: true
      env:
        - name: USER
          value: jenkins
        - name: JAVA_TOOL_OPTIONS
          value: -Duser.home=/home/jenkins/agent
      resources:
        requests:
          memory: 12Gi
          cpu: 6500m
        limits:
          memory: 14Gi
          cpu: 7500m
      volumeMounts:
        - mountPath: /home/jenkins/agent/.m2
          name: global-cache
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1 # Prefer instances with instance store volumes (NVMe SSD)
          preference:
            matchExpressions:
              - key: karpenter.k8s.aws/instance-local-nvme
                operator: Exists
        - weight: 1 # Prefer network optimized instances
          preference:
            matchExpressions:
              - key: karpenter.k8s.aws/instance-category
                operator: In
                values: ["n"]
  volumes:
    - name: global-cache
      persistentVolumeClaim:
        claimName: jenkins-agents-global-cache